// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PASgDR7Y4rmnZGwJ-2N5jC4p88hNnPM',
    appId: '1:566821005727:web:57a092d3bc4b4db26075aa',
    messagingSenderId: '566821005727',
    projectId: 'live-track-location-1c2d9',
    authDomain: 'live-track-location-1c2d9.firebaseapp.com',
    databaseURL: 'https://live-track-location-1c2d9-default-rtdb.firebaseio.com',
    storageBucket: 'live-track-location-1c2d9.firebasestorage.app',
    measurementId: 'G-3HGC9BB3QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebWwUJn-D13RWI2FFdYDTVD1PB6IOhvo',
    appId: '1:566821005727:android:53c31a7d402d2e4e6075aa',
    messagingSenderId: '566821005727',
    projectId: 'live-track-location-1c2d9',
    databaseURL: 'https://live-track-location-1c2d9-default-rtdb.firebaseio.com',
    storageBucket: 'live-track-location-1c2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzTJ2xhMSO48NTZi6Z_C5Rl4aspYK8Y0',
    appId: '1:566821005727:ios:5eee335436901b3b6075aa',
    messagingSenderId: '566821005727',
    projectId: 'live-track-location-1c2d9',
    databaseURL: 'https://live-track-location-1c2d9-default-rtdb.firebaseio.com',
    storageBucket: 'live-track-location-1c2d9.firebasestorage.app',
    iosBundleId: 'com.example.liveLocationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClzTJ2xhMSO48NTZi6Z_C5Rl4aspYK8Y0',
    appId: '1:566821005727:ios:5eee335436901b3b6075aa',
    messagingSenderId: '566821005727',
    projectId: 'live-track-location-1c2d9',
    databaseURL: 'https://live-track-location-1c2d9-default-rtdb.firebaseio.com',
    storageBucket: 'live-track-location-1c2d9.firebasestorage.app',
    iosBundleId: 'com.example.liveLocationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1PASgDR7Y4rmnZGwJ-2N5jC4p88hNnPM',
    appId: '1:566821005727:web:d66b94fa4359d62a6075aa',
    messagingSenderId: '566821005727',
    projectId: 'live-track-location-1c2d9',
    authDomain: 'live-track-location-1c2d9.firebaseapp.com',
    databaseURL: 'https://live-track-location-1c2d9-default-rtdb.firebaseio.com',
    storageBucket: 'live-track-location-1c2d9.firebasestorage.app',
    measurementId: 'G-QM93MC76VL',
  );
}
